package com.jmbmn.webservice.services.checkoutws.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2020-02-06T20:26:45.514-05:00
 * Generated source version: 3.1.16
 * 
 */
@WebServiceClient(name = "checkoutws", 
                  wsdlLocation = "file:/home/jhon/eclipse-workspace/webservice/src/main/resources/META-INF/wsdl/checkoutws.wsdl",
                  targetNamespace = "http://webservice.jmbmn.com/services/checkoutws/ws") 
public class Checkoutws extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.jmbmn.com/services/checkoutws/ws", "checkoutws");
    public final static QName CheckoutwsSOAP = new QName("http://webservice.jmbmn.com/services/checkoutws/ws", "checkoutwsSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/jhon/eclipse-workspace/webservice/src/main/resources/META-INF/wsdl/checkoutws.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Checkoutws.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/jhon/eclipse-workspace/webservice/src/main/resources/META-INF/wsdl/checkoutws.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Checkoutws(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Checkoutws(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Checkoutws() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Checkoutws(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Checkoutws(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Checkoutws(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Cardws
     */
    @WebEndpoint(name = "checkoutwsSOAP")
    public Cardws getCheckoutwsSOAP() {
        return super.getPort(CheckoutwsSOAP, Cardws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Cardws
     */
    @WebEndpoint(name = "checkoutwsSOAP")
    public Cardws getCheckoutwsSOAP(WebServiceFeature... features) {
        return super.getPort(CheckoutwsSOAP, Cardws.class, features);
    }

}
